version: "3.8"
services:
  react-app:
    image: anton83/react-app:ver1.0
    ports:
      - 80:80
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:my_pwd
    volumes:
      - postgres:/data/postgres
